# Generated by Django 4.1.7 on 2023-04-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
