# Generated by Django 4.1.7 on 2023-04-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_card_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="description",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="card",
            name="order",
            field=models.CharField(max_length=500),
        ),
    ]
