# Generated by Django 4.1.7 on 2023-04-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_card_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="board",
        ),
    ]
